server {
    listen 5173;
    root /usr/share/nginx/html;
    index index.html;

    # SPA fallback — всі маршрути повертають index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Кешування статики
    location ~* \.(js|css|png|jpg|svg|ico|woff2)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }
}
