# Generated by Django 5.0.6 on 2026-05-03 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_category_location_tag_delete_newspoint_location_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_clusters', models.IntegerField(verbose_name='Кількість кластерів')),
                ('result_json', models.JSONField(verbose_name='Результат кластеризації')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_results', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Результат кластеризації',
                'verbose_name_plural': 'Результати кластеризації',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адреса')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Переглянуто')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='locations.location', verbose_name='Локація')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_views', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Перегляд локації',
                'verbose_name_plural': 'Перегляди локацій',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
