# Generated by Django 6.0.4 on 2026-05-02 12:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_category_location_tag_delete_newspoint_location_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='geo_collections/', verbose_name='Обкладинка')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публічна')),
                ('invite_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('locations', models.ManyToManyField(blank=True, related_name='collections', to='locations.location', verbose_name='Локації')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='Власник')),
            ],
            options={
                'verbose_name': 'Колекція',
                'verbose_name_plural': 'Колекції',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Переглядач'), ('editor', 'Редактор')], default='viewer', max_length=10, verbose_name='Роль')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Приєднався')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='geo_collections.collection', verbose_name='Колекція')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Учасник колекції',
                'verbose_name_plural': 'Учасники колекцій',
                'unique_together': {('collection', 'user')},
            },
        ),
    ]
