# Generated by Django 6.0.4 on 2026-05-02 11:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок новини')),
                ('content', models.TextField(verbose_name='Зміст')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Місце події')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новина з геолокацією',
                'verbose_name_plural': 'Новини з геолокацією',
            },
        ),
    ]
